/**
 * Emoji RPG Builder - Activities & Sports Emoji Data
 * Contains emoji data for the Activities & Sports category
 */

const activitiesEmojis = [
    { emoji: "⚽", name: "soccer ball" },
    { emoji: "🏀", name: "basketball" },
    { emoji: "🏈", name: "american football" },
    { emoji: "⚾", name: "baseball" },
    { emoji: "🥎", name: "softball" },
    { emoji: "🎾", name: "tennis" },
    { emoji: "🏐", name: "volleyball" },
    { emoji: "🏉", name: "rugby football" },
    { emoji: "🥏", name: "flying disc" },
    { emoji: "🎱", name: "pool 8 ball" },
    { emoji: "🪀", name: "yo-yo" },
    { emoji: "🏓", name: "ping pong" },
    { emoji: "🏸", name: "badminton" },
    { emoji: "🏒", name: "ice hockey" },
    { emoji: "🏑", name: "field hockey" },
    { emoji: "🥍", name: "lacrosse" },
    { emoji: "🏏", name: "cricket game" },
    { emoji: "🪃", name: "boomerang" },
    { emoji: "🥅", name: "goal net" },
    { emoji: "⛳", name: "flag in hole" },
    { emoji: "🪁", name: "kite" },
    { emoji: "🏹", name: "bow and arrow" },
    { emoji: "🎣", name: "fishing pole" },
    { emoji: "🤿", name: "diving mask" },
    { emoji: "🥊", name: "boxing glove" },
    { emoji: "🥋", name: "martial arts uniform" },
    { emoji: "🎽", name: "running shirt" },
    { emoji: "🛹", name: "skateboard" },
    { emoji: "🛼", name: "roller skate" },
    { emoji: "🛷", name: "sled" },
    { emoji: "⛸️", name: "ice skate" },
    { emoji: "🥌", name: "curling stone" },
    { emoji: "🎯", name: "direct hit" },
    { emoji: "🪄", name: "magic wand" },
    { emoji: "🎪", name: "circus tent" },
    { emoji: "🎭", name: "performing arts" },
    { emoji: "🎨", name: "artist palette" },
    { emoji: "🎬", name: "clapper board" },
    { emoji: "🎤", name: "microphone" },
    { emoji: "🎧", name: "headphone" },
    { emoji: "🎼", name: "musical score" },
    { emoji: "🎹", name: "musical keyboard" },
    { emoji: "🥁", name: "drum" },
    { emoji: "🎷", name: "saxophone" },
    { emoji: "🎺", name: "trumpet" },
    { emoji: "🎸", name: "guitar" },
    { emoji: "🪕", name: "banjo" },
    { emoji: "🎻", name: "violin" },
    { emoji: "🎲", name: "game die" },
    { emoji: "♟️", name: "chess pawn" },
    { emoji: "🎯", name: "direct hit" },
    { emoji: "🎳", name: "bowling" },
    { emoji: "🎮", name: "video game" },
    { emoji: "🎰", name: "slot machine" },
    { emoji: "🧩", name: "puzzle piece" }
];

export default activitiesEmojis;
