/**
 * Emoji RPG Builder - Food & Drink Emoji Data
 * Contains emoji data for the Food & Drink category
 */

const foodEmojis = [
    { emoji: "🍏", name: "green apple" },
    { emoji: "🍎", name: "red apple" },
    { emoji: "🍐", name: "pear" },
    { emoji: "🍊", name: "tangerine" },
    { emoji: "🍋", name: "lemon" },
    { emoji: "🍌", name: "banana" },
    { emoji: "🍉", name: "watermelon" },
    { emoji: "🍇", name: "grapes" },
    { emoji: "🍓", name: "strawberry" },
    { emoji: "🍈", name: "melon" },
    { emoji: "🍒", name: "cherries" },
    { emoji: "🍑", name: "peach" },
    { emoji: "🍍", name: "pineapple" },
    { emoji: "🥭", name: "mango" },
    { emoji: "🍅", name: "tomato" },
    { emoji: "🍆", name: "eggplant" },
    { emoji: "🥑", name: "avocado" },
    { emoji: "🥒", name: "cucumber" },
    { emoji: "🥦", name: "broccoli" },
    { emoji: "🌽", name: "ear of corn" },
    { emoji: "🥕", name: "carrot" },
    { emoji: "🧄", name: "garlic" },
    { emoji: "🧅", name: "onion" },
    { emoji: "🥔", name: "potato" },
    { emoji: "🍞", name: "bread" },
    { emoji: "🥐", name: "croissant" },
    { emoji: "🥖", name: "baguette bread" },
    { emoji: "🥨", name: "pretzel" },
    { emoji: "🧀", name: "cheese wedge" },
    { emoji: "🥚", name: "egg" },
    { emoji: "🍳", name: "cooking" },
    { emoji: "🥓", name: "bacon" },
    { emoji: "🥩", name: "cut of meat" },
    { emoji: "🍗", name: "poultry leg" },
    { emoji: "🍖", name: "meat on bone" },
    { emoji: "🌭", name: "hot dog" },
    { emoji: "🍔", name: "hamburger" },
    { emoji: "🍟", name: "french fries" },
    { emoji: "🍕", name: "pizza" },
    { emoji: "🌮", name: "taco" },
    { emoji: "🌯", name: "burrito" },
    { emoji: "🥙", name: "stuffed flatbread" },
    { emoji: "🍝", name: "spaghetti" },
    { emoji: "🍜", name: "steaming bowl" },
    { emoji: "🍲", name: "pot of food" },
    { emoji: "🍛", name: "curry rice" },
    { emoji: "🍚", name: "cooked rice" },
    { emoji: "🍙", name: "rice ball" },
    { emoji: "🍣", name: "sushi" },
    { emoji: "🍤", name: "fried shrimp" },
    { emoji: "🍦", name: "soft ice cream" },
    { emoji: "🍧", name: "shaved ice" },
    { emoji: "🍨", name: "ice cream" },
    { emoji: "🍩", name: "doughnut" },
    { emoji: "🍪", name: "cookie" },
    { emoji: "🎂", name: "birthday cake" },
    { emoji: "🍰", name: "shortcake" },
    { emoji: "🧁", name: "cupcake" },
    { emoji: "🥧", name: "pie" },
    { emoji: "🍫", name: "chocolate bar" },
    { emoji: "🍬", name: "candy" },
    { emoji: "🍭", name: "lollipop" },
    { emoji: "🍮", name: "custard" },
    { emoji: "🍯", name: "honey pot" },
    { emoji: "🍼", name: "baby bottle" },
    { emoji: "🥛", name: "glass of milk" },
    { emoji: "☕", name: "hot beverage" },
    { emoji: "🍵", name: "teacup without handle" },
    { emoji: "🍶", name: "sake" },
    { emoji: "🍾", name: "bottle with popping cork" },
    { emoji: "🍷", name: "wine glass" },
    { emoji: "🍸", name: "cocktail glass" },
    { emoji: "🍹", name: "tropical drink" },
    { emoji: "🍺", name: "beer mug" },
    { emoji: "🍻", name: "clinking beer mugs" },
    { emoji: "🥂", name: "clinking glasses" },
    { emoji: "🥃", name: "tumbler glass" },
    { emoji: "🥤", name: "cup with straw" },
    { emoji: "🧃", name: "beverage box" },
    { emoji: "🧊", name: "ice cube" }
];

export default foodEmojis;
