/**
 * Emoji RPG Builder - Animals & Nature Emoji Data
 * Contains emoji data for the Animals & Nature category
 */

const natureEmojis = [
    { emoji: "🐵", name: "monkey face" },
    { emoji: "🐒", name: "monkey" },
    { emoji: "🦍", name: "gorilla" },
    { emoji: "🦧", name: "orangutan" },
    { emoji: "🐶", name: "dog face" },
    { emoji: "🐕", name: "dog" },
    { emoji: "🦮", name: "guide dog" },
    { emoji: "🐩", name: "poodle" },
    { emoji: "🐺", name: "wolf" },
    { emoji: "🦊", name: "fox" },
    { emoji: "🦝", name: "raccoon" },
    { emoji: "🐱", name: "cat face" },
    { emoji: "🐈", name: "cat" },
    { emoji: "🦁", name: "lion" },
    { emoji: "🐯", name: "tiger face" },
    { emoji: "🐅", name: "tiger" },
    { emoji: "🐆", name: "leopard" },
    { emoji: "🐴", name: "horse face" },
    { emoji: "🐎", name: "horse" },
    { emoji: "🦄", name: "unicorn" },
    { emoji: "🦓", name: "zebra" },
    { emoji: "🦌", name: "deer" },
    { emoji: "🐮", name: "cow face" },
    { emoji: "🐂", name: "ox" },
    { emoji: "🐃", name: "water buffalo" },
    { emoji: "🐄", name: "cow" },
    { emoji: "🐷", name: "pig face" },
    { emoji: "🐖", name: "pig" },
    { emoji: "🐗", name: "boar" },
    { emoji: "🐽", name: "pig nose" },
    { emoji: "🐏", name: "ram" },
    { emoji: "🐑", name: "ewe" },
    { emoji: "🐐", name: "goat" },
    { emoji: "🐪", name: "camel" },
    { emoji: "🐫", name: "two-hump camel" },
    { emoji: "🦙", name: "llama" },
    { emoji: "🦒", name: "giraffe" },
    { emoji: "🐘", name: "elephant" },
    { emoji: "🦏", name: "rhinoceros" },
    { emoji: "🦛", name: "hippopotamus" },
    { emoji: "🐭", name: "mouse face" },
    { emoji: "🐁", name: "mouse" },
    { emoji: "🐀", name: "rat" },
    { emoji: "🐹", name: "hamster" },
    { emoji: "🐰", name: "rabbit face" },
    { emoji: "🐇", name: "rabbit" },
    { emoji: "🐿️", name: "chipmunk" },
    { emoji: "🦔", name: "hedgehog" },
    { emoji: "🦇", name: "bat" },
    { emoji: "🐻", name: "bear" },
    { emoji: "🐨", name: "koala" },
    { emoji: "🐼", name: "panda" },
    { emoji: "🦥", name: "sloth" },
    { emoji: "🦦", name: "otter" },
    { emoji: "🦨", name: "skunk" },
    { emoji: "🦘", name: "kangaroo" },
    { emoji: "🦡", name: "badger" },
    { emoji: "🐾", name: "paw prints" },
    { emoji: "🦃", name: "turkey" },
    { emoji: "🐔", name: "chicken" },
    { emoji: "🐓", name: "rooster" },
    { emoji: "🐣", name: "hatching chick" },
    { emoji: "🐤", name: "baby chick" },
    { emoji: "🐥", name: "front-facing baby chick" },
    { emoji: "🐦", name: "bird" },
    { emoji: "🐧", name: "penguin" },
    { emoji: "🕊️", name: "dove" },
    { emoji: "🦅", name: "eagle" },
    { emoji: "🦆", name: "duck" },
    { emoji: "🦢", name: "swan" },
    { emoji: "🦉", name: "owl" },
    { emoji: "🦩", name: "flamingo" },
    { emoji: "🦚", name: "peacock" },
    { emoji: "🦜", name: "parrot" },
    { emoji: "🐸", name: "frog" },
    { emoji: "🐊", name: "crocodile" },
    { emoji: "🐢", name: "turtle" },
    { emoji: "🦎", name: "lizard" },
    { emoji: "🐍", name: "snake" },
    { emoji: "🐲", name: "dragon face" },
    { emoji: "🐉", name: "dragon" },
    { emoji: "🦕", name: "sauropod" },
    { emoji: "🦖", name: "T-Rex" },
    { emoji: "🐳", name: "spouting whale" },
    { emoji: "🐋", name: "whale" },
    { emoji: "🐬", name: "dolphin" },
    { emoji: "🐟", name: "fish" },
    { emoji: "🐠", name: "tropical fish" },
    { emoji: "🐡", name: "blowfish" },
    { emoji: "🦈", name: "shark" },
    { emoji: "🐙", name: "octopus" },
    { emoji: "🐚", name: "spiral shell" },
    { emoji: "🐌", name: "snail" },
    { emoji: "🦋", name: "butterfly" },
    { emoji: "🐛", name: "bug" },
    { emoji: "🐜", name: "ant" },
    { emoji: "🐝", name: "honeybee" },
    { emoji: "🐞", name: "lady beetle" },
    { emoji: "🕷️", name: "spider" },
    { emoji: "🕸️", name: "spider web" },
    { emoji: "🦂", name: "scorpion" },
    { emoji: "🦟", name: "mosquito" },
    { emoji: "🦠", name: "microbe" },
    { emoji: "💐", name: "bouquet" },
    { emoji: "🌸", name: "cherry blossom" },
    { emoji: "💮", name: "white flower" },
    { emoji: "🌹", name: "rose" },
    { emoji: "🥀", name: "wilted flower" },
    { emoji: "🌺", name: "hibiscus" },
    { emoji: "🌻", name: "sunflower" },
    { emoji: "🌼", name: "blossom" },
    { emoji: "🌷", name: "tulip" },
    { emoji: "🌱", name: "seedling" },
    { emoji: "🌲", name: "evergreen tree" },
    { emoji: "🌳", name: "deciduous tree" },
    { emoji: "🌴", name: "palm tree" },
    { emoji: "🌵", name: "cactus" },
    { emoji: "🌾", name: "sheaf of rice" },
    { emoji: "🌿", name: "herb" },
    { emoji: "☘️", name: "shamrock" },
    { emoji: "🍀", name: "four leaf clover" },
    { emoji: "🍁", name: "maple leaf" },
    { emoji: "🍂", name: "fallen leaf" },
    { emoji: "🍃", name: "leaf fluttering in wind" },
    { emoji: "🍄", name: "mushroom" }
];

export default natureEmojis;
