/**
 * Emoji RPG Builder - Objects Emoji Data
 * Contains emoji data for the Objects category
 */

const objectsEmojis = [
    { emoji: "📱", name: "Mobile Phone" },
    { emoji: "💻", name: "Laptop" },
    { emoji: "⌚", name: "Watch" },
    { emoji: "⏰", name: "Alarm Clock" },
    { emoji: "🔋", name: "Battery" },
    { emoji: "💡", name: "Light Bulb" },
    { emoji: "🔦", name: "Flashlight" },
    { emoji: "🔍", name: "Magnifying Glass" },
    { emoji: "🔑", name: "Key" },
    { emoji: "🔒", name: "Lock" },
    { emoji: "🔓", name: "Unlock" },
    { emoji: "🧰", name: "Toolbox" },
    { emoji: "🔨", name: "Hammer" },
    { emoji: "🪓", name: "Axe" },
    { emoji: "⛏️", name: "Pick" },
    { emoji: "🔧", name: "Wrench" },
    { emoji: "🪛", name: "Screwdriver" },
    { emoji: "📌", name: "Pushpin" },
    { emoji: "📎", name: "Paperclip" },
    { emoji: "✂️", name: "Scissors" },
    { emoji: "🧷", name: "Safety Pin" },
    { emoji: "📏", name: "Ruler" },
    { emoji: "📐", name: "Triangle Ruler" },
    { emoji: "📦", name: "Package" },
    { emoji: "📫", name: "Mailbox" },
    { emoji: "📧", name: "Email" },
    { emoji: "📝", name: "Memo" },
    { emoji: "📁", name: "File Folder" },
    { emoji: "📂", name: "Open File Folder" },
    { emoji: "🗂️", name: "Card Index Dividers" },
    { emoji: "📅", name: "Calendar" },
    { emoji: "📊", name: "Bar Chart" },
    { emoji: "📈", name: "Chart Increasing" },
    { emoji: "📉", name: "Chart Decreasing" },
    { emoji: "📋", name: "Clipboard" },
    { emoji: "📌", name: "Pushpin" },
    { emoji: "📍", name: "Round Pushpin" },
    { emoji: "📎", name: "Paperclip" },
    { emoji: "🖇️", name: "Linked Paperclips" },
    { emoji: "📔", name: "Notebook with Decorative Cover" },
    { emoji: "📕", name: "Closed Book" },
    { emoji: "📖", name: "Open Book" },
    { emoji: "📗", name: "Green Book" },
    { emoji: "📘", name: "Blue Book" },
    { emoji: "📙", name: "Orange Book" },
    { emoji: "📚", name: "Books" },
    { emoji: "🔖", name: "Bookmark" },
    { emoji: "🧮", name: "Abacus" },
    { emoji: "🎮", name: "Video Game" },
    { emoji: "🎲", name: "Game Die" },
    { emoji: "🎯", name: "Bullseye" },
    { emoji: "🎰", name: "Slot Machine" },
    { emoji: "🧩", name: "Puzzle Piece" },
    { emoji: "🪄", name: "Magic Wand" },
    { emoji: "🧸", name: "Teddy Bear" },
    { emoji: "🪆", name: "Nesting Dolls" },
    { emoji: "🧶", name: "Yarn" },
    { emoji: "🧵", name: "Thread" },
    { emoji: "🧣", name: "Scarf" },
    { emoji: "🧤", name: "Gloves" },
    { emoji: "👓", name: "Glasses" },
    { emoji: "🕶️", name: "Sunglasses" },
    { emoji: "👔", name: "Necktie" },
    { emoji: "👕", name: "T-Shirt" },
    { emoji: "👖", name: "Jeans" },
    { emoji: "🧦", name: "Socks" },
    { emoji: "👗", name: "Dress" },
    { emoji: "👘", name: "Kimono" },
    { emoji: "👙", name: "Bikini" },
    { emoji: "🎒", name: "Backpack" },
    { emoji: "👜", name: "Handbag" },
    { emoji: "💼", name: "Briefcase" },
    { emoji: "🧳", name: "Luggage" },
    { emoji: "💍", name: "Ring" },
    { emoji: "💎", name: "Gem Stone" },
    { emoji: "🔔", name: "Bell" },
    { emoji: "🎵", name: "Musical Note" },
    { emoji: "🎸", name: "Guitar" },
    { emoji: "🎹", name: "Piano" },
    { emoji: "🎺", name: "Trumpet" },
    { emoji: "🎻", name: "Violin" },
    { emoji: "🥁", name: "Drum" },
    { emoji: "🪘", name: "Long Drum" },
    { emoji: "🎬", name: "Clapper Board" },
    { emoji: "🎨", name: "Artist Palette" },
    { emoji: "🧪", name: "Test Tube" },
    { emoji: "🧫", name: "Petri Dish" },
    { emoji: "🧬", name: "DNA" },
    { emoji: "🔬", name: "Microscope" },
    { emoji: "🔭", name: "Telescope" },
    { emoji: "📡", name: "Satellite Antenna" },
    { emoji: "💉", name: "Syringe" },
    { emoji: "🩸", name: "Drop of Blood" },
    { emoji: "💊", name: "Pill" },
    { emoji: "🩹", name: "Adhesive Bandage" },
    { emoji: "🩺", name: "Stethoscope" },
    { emoji: "🚪", name: "Door" },
    { emoji: "🪑", name: "Chair" },
    { emoji: "🛏️", name: "Bed" },
    { emoji: "🪞", name: "Mirror" },
    { emoji: "🪟", name: "Window" },
    { emoji: "🛁", name: "Bathtub" },
    { emoji: "🚽", name: "Toilet" },
    { emoji: "🚿", name: "Shower" },
    { emoji: "🧴", name: "Lotion Bottle" },
    { emoji: "🧹", name: "Broom" },
    { emoji: "🧺", name: "Basket" },
    { emoji: "🧻", name: "Roll of Paper" },
    { emoji: "🪣", name: "Bucket" },
    { emoji: "🧼", name: "Soap" },
    { emoji: "🪥", name: "Toothbrush" },
    { emoji: "🧽", name: "Sponge" },
    { emoji: "🧯", name: "Fire Extinguisher" },
    { emoji: "🔥", name: "Fire" },
    { emoji: "💧", name: "Droplet" },
    { emoji: "🧊", name: "Ice Cube" }
];

export default objectsEmojis;
