/**
 * Emoji RPG Builder - People & Faces Emoji Data
 * Contains emoji data for the People & Faces category
 */

const peopleEmojis = [
    { emoji: "😀", name: "grinning face" },
    { emoji: "😃", name: "grinning face with big eyes" },
    { emoji: "😄", name: "grinning face with smiling eyes" },
    { emoji: "😁", name: "beaming face with smiling eyes" },
    { emoji: "😆", name: "grinning squinting face" },
    { emoji: "😅", name: "grinning face with sweat" },
    { emoji: "🤣", name: "rolling on the floor laughing" },
    { emoji: "😂", name: "face with tears of joy" },
    { emoji: "🙂", name: "slightly smiling face" },
    { emoji: "🙃", name: "upside-down face" },
    { emoji: "😉", name: "winking face" },
    { emoji: "😊", name: "smiling face with smiling eyes" },
    { emoji: "😇", name: "smiling face with halo" },
    { emoji: "🥰", name: "smiling face with hearts" },
    { emoji: "😍", name: "smiling face with heart-eyes" },
    { emoji: "🤩", name: "star-struck" },
    { emoji: "😘", name: "face blowing a kiss" },
    { emoji: "😗", name: "kissing face" },
    { emoji: "☺️", name: "smiling face" },
    { emoji: "😚", name: "kissing face with closed eyes" },
    { emoji: "😙", name: "kissing face with smiling eyes" },
    { emoji: "🥲", name: "smiling face with tear" },
    { emoji: "😋", name: "face savoring food" },
    { emoji: "😛", name: "face with tongue" },
    { emoji: "😜", name: "winking face with tongue" },
    { emoji: "🤪", name: "zany face" },
    { emoji: "😝", name: "squinting face with tongue" },
    { emoji: "🤑", name: "money-mouth face" },
    { emoji: "🤗", name: "hugging face" },
    { emoji: "🤭", name: "face with hand over mouth" },
    { emoji: "🤫", name: "shushing face" },
    { emoji: "🤔", name: "thinking face" },
    { emoji: "🤐", name: "zipper-mouth face" },
    { emoji: "🤨", name: "face with raised eyebrow" },
    { emoji: "😐", name: "neutral face" },
    { emoji: "😑", name: "expressionless face" },
    { emoji: "😶", name: "face without mouth" },
    { emoji: "😏", name: "smirking face" },
    { emoji: "😒", name: "unamused face" },
    { emoji: "🙄", name: "face with rolling eyes" },
    { emoji: "😬", name: "grimacing face" },
    { emoji: "🤥", name: "lying face" },
    { emoji: "😌", name: "relieved face" },
    { emoji: "😔", name: "pensive face" },
    { emoji: "😪", name: "sleepy face" },
    { emoji: "🤤", name: "drooling face" },
    { emoji: "😴", name: "sleeping face" },
    { emoji: "😷", name: "face with medical mask" },
    { emoji: "🤒", name: "face with thermometer" },
    { emoji: "🤕", name: "face with head-bandage" },
    { emoji: "🤢", name: "nauseated face" },
    { emoji: "🤮", name: "face vomiting" },
    { emoji: "🤧", name: "sneezing face" },
    { emoji: "🥵", name: "hot face" },
    { emoji: "🥶", name: "cold face" },
    { emoji: "🥴", name: "woozy face" },
    { emoji: "😵", name: "dizzy face" },
    { emoji: "🤯", name: "exploding head" },
    { emoji: "🤠", name: "cowboy hat face" },
    { emoji: "🥳", name: "partying face" },
    { emoji: "😎", name: "smiling face with sunglasses" },
    { emoji: "🤓", name: "nerd face" },
    { emoji: "🧐", name: "face with monocle" },
    { emoji: "😕", name: "confused face" },
    { emoji: "😟", name: "worried face" },
    { emoji: "🙁", name: "slightly frowning face" },
    { emoji: "☹️", name: "frowning face" },
    { emoji: "😮", name: "face with open mouth" },
    { emoji: "😯", name: "hushed face" },
    { emoji: "😲", name: "astonished face" },
    { emoji: "😳", name: "flushed face" },
    { emoji: "🥺", name: "pleading face" },
    { emoji: "😦", name: "frowning face with open mouth" },
    { emoji: "😧", name: "anguished face" },
    { emoji: "😨", name: "fearful face" },
    { emoji: "😰", name: "anxious face with sweat" },
    { emoji: "😥", name: "sad but relieved face" },
    { emoji: "😢", name: "crying face" },
    { emoji: "😭", name: "loudly crying face" },
    { emoji: "😱", name: "face screaming in fear" },
    { emoji: "😖", name: "confounded face" },
    { emoji: "😣", name: "persevering face" },
    { emoji: "😞", name: "disappointed face" },
    { emoji: "😓", name: "downcast face with sweat" },
    { emoji: "😩", name: "weary face" },
    { emoji: "😫", name: "tired face" },
    { emoji: "🥱", name: "yawning face" },
    { emoji: "😤", name: "face with steam from nose" },
    { emoji: "😡", name: "pouting face" },
    { emoji: "😠", name: "angry face" },
    { emoji: "🤬", name: "face with symbols on mouth" },
    { emoji: "😈", name: "smiling face with horns" },
    { emoji: "👿", name: "angry face with horns" },
    { emoji: "💀", name: "skull" },
    { emoji: "☠️", name: "skull and crossbones" },
    { emoji: "💩", name: "pile of poo" },
    { emoji: "🤡", name: "clown face" },
    { emoji: "👹", name: "ogre" },
    { emoji: "👺", name: "goblin" },
    { emoji: "👻", name: "ghost" },
    { emoji: "👽", name: "alien" },
    { emoji: "👾", name: "alien monster" },
    { emoji: "🤖", name: "robot" }
];

export default peopleEmojis;
