/**
 * Emoji RPG Builder - Symbols Emoji Data
 * Contains emoji data for the Symbols category
 */

const symbolsEmojis = [
    { emoji: "❤️", name: "Red Heart" },
    { emoji: "🧡", name: "Orange Heart" },
    { emoji: "💛", name: "Yellow Heart" },
    { emoji: "💚", name: "Green Heart" },
    { emoji: "💙", name: "Blue Heart" },
    { emoji: "💜", name: "Purple Heart" },
    { emoji: "🖤", name: "Black Heart" },
    { emoji: "🤍", name: "White Heart" },
    { emoji: "🤎", name: "Brown Heart" },
    { emoji: "💔", name: "Broken Heart" },
    { emoji: "❣️", name: "Heart Exclamation" },
    { emoji: "💕", name: "Two Hearts" },
    { emoji: "💞", name: "Revolving Hearts" },
    { emoji: "💓", name: "Beating Heart" },
    { emoji: "💗", name: "Growing Heart" },
    { emoji: "💖", name: "Sparkling Heart" },
    { emoji: "💘", name: "Heart with Arrow" },
    { emoji: "💝", name: "Heart with Ribbon" },
    { emoji: "💟", name: "Heart Decoration" },
    { emoji: "☮️", name: "Peace Symbol" },
    { emoji: "✝️", name: "Latin Cross" },
    { emoji: "☪️", name: "Star and Crescent" },
    { emoji: "🕉️", name: "Om" },
    { emoji: "☸️", name: "Wheel of Dharma" },
    { emoji: "✡️", name: "Star of David" },
    { emoji: "🔯", name: "Six Pointed Star" },
    { emoji: "🕎", name: "Menorah" },
    { emoji: "☯️", name: "Yin Yang" },
    { emoji: "☦️", name: "Orthodox Cross" },
    { emoji: "🛐", name: "Place of Worship" },
    { emoji: "⛎", name: "Ophiuchus" },
    { emoji: "♈", name: "Aries" },
    { emoji: "♉", name: "Taurus" },
    { emoji: "♊", name: "Gemini" },
    { emoji: "♋", name: "Cancer" },
    { emoji: "♌", name: "Leo" },
    { emoji: "♍", name: "Virgo" },
    { emoji: "♎", name: "Libra" },
    { emoji: "♏", name: "Scorpio" },
    { emoji: "♐", name: "Sagittarius" },
    { emoji: "♑", name: "Capricorn" },
    { emoji: "♒", name: "Aquarius" },
    { emoji: "♓", name: "Pisces" },
    { emoji: "🆔", name: "ID Button" },
    { emoji: "⚛️", name: "Atom Symbol" },
    { emoji: "🉑", name: "Japanese Acceptable Button" },
    { emoji: "☢️", name: "Radioactive" },
    { emoji: "☣️", name: "Biohazard" },
    { emoji: "📴", name: "Mobile Phone Off" },
    { emoji: "📳", name: "Vibration Mode" },
    { emoji: "🈶", name: "Japanese Not Free of Charge Button" },
    { emoji: "🈚", name: "Japanese Free of Charge Button" },
    { emoji: "🈸", name: "Japanese Application Button" },
    { emoji: "🈺", name: "Japanese Open for Business Button" },
    { emoji: "🈷️", name: "Japanese Monthly Amount Button" },
    { emoji: "✴️", name: "Eight-Pointed Star" },
    { emoji: "🆚", name: "VS Button" },
    { emoji: "💮", name: "White Flower" },
    { emoji: "🉐", name: "Japanese Bargain Button" },
    { emoji: "㊙️", name: "Japanese Secret Button" },
    { emoji: "㊗️", name: "Japanese Congratulations Button" },
    { emoji: "🈴", name: "Japanese Passing Grade Button" },
    { emoji: "🈵", name: "Japanese No Vacancy Button" },
    { emoji: "🈹", name: "Japanese Discount Button" },
    { emoji: "🈲", name: "Japanese Prohibited Button" },
    { emoji: "🅰️", name: "A Button (Blood Type)" },
    { emoji: "🅱️", name: "B Button (Blood Type)" },
    { emoji: "🆎", name: "AB Button (Blood Type)" },
    { emoji: "🆑", name: "CL Button" },
    { emoji: "🅾️", name: "O Button (Blood Type)" },
    { emoji: "🆘", name: "SOS Button" },
    { emoji: "❌", name: "Cross Mark" },
    { emoji: "⭕", name: "Hollow Red Circle" },
    { emoji: "🛑", name: "Stop Sign" },
    { emoji: "⛔", name: "No Entry" },
    { emoji: "📛", name: "Name Badge" },
    { emoji: "🚫", name: "Prohibited" },
    { emoji: "💯", name: "Hundred Points" },
    { emoji: "💢", name: "Anger Symbol" },
    { emoji: "♨️", name: "Hot Springs" },
    { emoji: "🚷", name: "No Pedestrians" },
    { emoji: "🚯", name: "No Littering" },
    { emoji: "🚳", name: "No Bicycles" },
    { emoji: "🚱", name: "Non-Potable Water" },
    { emoji: "🔞", name: "No One Under Eighteen" },
    { emoji: "📵", name: "No Mobile Phones" },
    { emoji: "🚭", name: "No Smoking" },
    { emoji: "❗", name: "Exclamation Mark" },
    { emoji: "❕", name: "White Exclamation Mark" },
    { emoji: "❓", name: "Question Mark" },
    { emoji: "❔", name: "White Question Mark" },
    { emoji: "‼️", name: "Double Exclamation Mark" },
    { emoji: "⁉️", name: "Exclamation Question Mark" },
    { emoji: "🔅", name: "Dim Button" },
    { emoji: "🔆", name: "Bright Button" },
    { emoji: "〽️", name: "Part Alternation Mark" },
    { emoji: "⚠️", name: "Warning" },
    { emoji: "🚸", name: "Children Crossing" },
    { emoji: "🔱", name: "Trident Emblem" },
    { emoji: "⚜️", name: "Fleur-de-lis" },
    { emoji: "🔰", name: "Japanese Symbol for Beginner" },
    { emoji: "♻️", name: "Recycling Symbol" },
    { emoji: "✅", name: "Check Mark Button" },
    { emoji: "🈯", name: "Japanese Reserved Button" },
    { emoji: "💹", name: "Chart Increasing with Yen" },
    { emoji: "❇️", name: "Sparkle" },
    { emoji: "✳️", name: "Eight-Spoked Asterisk" },
    { emoji: "❎", name: "Cross Mark Button" },
    { emoji: "🌐", name: "Globe with Meridians" },
    { emoji: "💠", name: "Diamond with a Dot" },
    { emoji: "Ⓜ️", name: "Circled M" },
    { emoji: "🌀", name: "Cyclone" },
    { emoji: "💤", name: "Zzz" },
    { emoji: "🏧", name: "ATM Sign" },
    { emoji: "🚾", name: "Water Closet" },
    { emoji: "♿", name: "Wheelchair Symbol" },
    { emoji: "🅿️", name: "P Button" },
    { emoji: "🛗", name: "Elevator" },
    { emoji: "🚹", name: "Men's Room" },
    { emoji: "🚺", name: "Women's Room" },
    { emoji: "🚼", name: "Baby Symbol" },
    { emoji: "⚧️", name: "Transgender Symbol" },
    { emoji: "🚻", name: "Restroom" },
    { emoji: "🚮", name: "Litter in Bin Sign" },
    { emoji: "🎦", name: "Cinema" },
    { emoji: "📶", name: "Antenna Bars" },
    { emoji: "🈁", name: "Japanese Here Button" },
    { emoji: "🔣", name: "Input Symbols" },
    { emoji: "ℹ️", name: "Information" },
    { emoji: "🔤", name: "Input Latin Letters" },
    { emoji: "🔡", name: "Input Latin Lowercase" },
    { emoji: "🔠", name: "Input Latin Uppercase" },
    { emoji: "🆖", name: "NG Button" },
    { emoji: "🆗", name: "OK Button" },
    { emoji: "🆙", name: "UP! Button" },
    { emoji: "🆒", name: "COOL Button" },
    { emoji: "🆕", name: "NEW Button" },
    { emoji: "🆓", name: "FREE Button" },
    { emoji: "0️⃣", name: "Keycap: 0" },
    { emoji: "1️⃣", name: "Keycap: 1" },
    { emoji: "2️⃣", name: "Keycap: 2" },
    { emoji: "3️⃣", name: "Keycap: 3" },
    { emoji: "4️⃣", name: "Keycap: 4" },
    { emoji: "5️⃣", name: "Keycap: 5" },
    { emoji: "6️⃣", name: "Keycap: 6" },
    { emoji: "7️⃣", name: "Keycap: 7" },
    { emoji: "8️⃣", name: "Keycap: 8" },
    { emoji: "9️⃣", name: "Keycap: 9" },
    { emoji: "🔟", name: "Keycap: 10" },
    { emoji: "🔢", name: "Input Numbers" },
    { emoji: "#️⃣", name: "Keycap: #" },
    { emoji: "*️⃣", name: "Keycap: *" },
    { emoji: "⏏️", name: "Eject Button" },
    { emoji: "▶️", name: "Play Button" },
    { emoji: "⏸️", name: "Pause Button" },
    { emoji: "⏯️", name: "Play or Pause Button" },
    { emoji: "⏹️", name: "Stop Button" },
    { emoji: "⏺️", name: "Record Button" },
    { emoji: "⏭️", name: "Next Track Button" },
    { emoji: "⏮️", name: "Last Track Button" },
    { emoji: "⏩", name: "Fast-Forward Button" },
    { emoji: "⏪", name: "Fast Reverse Button" },
    { emoji: "⏫", name: "Fast Up Button" },
    { emoji: "⏬", name: "Fast Down Button" },
    { emoji: "◀️", name: "Reverse Button" },
    { emoji: "🔼", name: "Upwards Button" },
    { emoji: "🔽", name: "Downwards Button" },
    { emoji: "➡️", name: "Right Arrow" },
    { emoji: "⬅️", name: "Left Arrow" },
    { emoji: "⬆️", name: "Up Arrow" },
    { emoji: "⬇️", name: "Down Arrow" },
    { emoji: "↗️", name: "Up-Right Arrow" },
    { emoji: "↘️", name: "Down-Right Arrow" },
    { emoji: "↙️", name: "Down-Left Arrow" },
    { emoji: "↖️", name: "Up-Left Arrow" },
    { emoji: "↕️", name: "Up-Down Arrow" },
    { emoji: "↔️", name: "Left-Right Arrow" },
    { emoji: "↪️", name: "Left Arrow Curving Right" },
    { emoji: "↩️", name: "Right Arrow Curving Left" },
    { emoji: "⤴️", name: "Right Arrow Curving Up" },
    { emoji: "⤵️", name: "Right Arrow Curving Down" },
    { emoji: "🔀", name: "Shuffle Tracks Button" },
    { emoji: "🔁", name: "Repeat Button" },
    { emoji: "🔂", name: "Repeat Single Button" },
    { emoji: "🔄", name: "Counterclockwise Arrows Button" },
    { emoji: "🔃", name: "Clockwise Vertical Arrows" },
    { emoji: "🎵", name: "Musical Note" },
    { emoji: "🎶", name: "Musical Notes" },
    { emoji: "➕", name: "Plus" },
    { emoji: "➖", name: "Minus" },
    { emoji: "➗", name: "Division" },
    { emoji: "✖️", name: "Multiplication" },
    { emoji: "♾️", name: "Infinity" },
    { emoji: "💲", name: "Heavy Dollar Sign" },
    { emoji: "💱", name: "Currency Exchange" },
    { emoji: "™️", name: "Trade Mark" },
    { emoji: "©️", name: "Copyright" },
    { emoji: "®️", name: "Registered" },
    { emoji: "〰️", name: "Wavy Dash" },
    { emoji: "➰", name: "Curly Loop" },
    { emoji: "➿", name: "Double Curly Loop" },
    { emoji: "🔚", name: "END Arrow" },
    { emoji: "🔙", name: "BACK Arrow" },
    { emoji: "🔛", name: "ON! Arrow" },
    { emoji: "🔝", name: "TOP Arrow" },
    { emoji: "🔜", name: "SOON Arrow" },
    { emoji: "✔️", name: "Check Mark" },
    { emoji: "☑️", name: "Check Box with Check" },
    { emoji: "🔘", name: "Radio Button" },
    { emoji: "🔴", name: "Red Circle" },
    { emoji: "🟠", name: "Orange Circle" },
    { emoji: "🟡", name: "Yellow Circle" },
    { emoji: "🟢", name: "Green Circle" },
    { emoji: "🔵", name: "Blue Circle" },
    { emoji: "🟣", name: "Purple Circle" },
    { emoji: "⚫", name: "Black Circle" },
    { emoji: "⚪", name: "White Circle" },
    { emoji: "🟤", name: "Brown Circle" },
    { emoji: "🔺", name: "Red Triangle Pointed Up" },
    { emoji: "🔻", name: "Red Triangle Pointed Down" },
    { emoji: "🔸", name: "Small Orange Diamond" },
    { emoji: "🔹", name: "Small Blue Diamond" },
    { emoji: "🔶", name: "Large Orange Diamond" },
    { emoji: "🔷", name: "Large Blue Diamond" },
    { emoji: "🔳", name: "White Square Button" },
    { emoji: "🔲", name: "Black Square Button" },
    { emoji: "▪️", name: "Black Small Square" },
    { emoji: "▫️", name: "White Small Square" },
    { emoji: "◾", name: "Black Medium-Small Square" },
    { emoji: "◽", name: "White Medium-Small Square" },
    { emoji: "◼️", name: "Black Medium Square" },
    { emoji: "◻️", name: "White Medium Square" },
    { emoji: "🟥", name: "Red Square" },
    { emoji: "🟧", name: "Orange Square" },
    { emoji: "🟨", name: "Yellow Square" },
    { emoji: "🟩", name: "Green Square" },
    { emoji: "🟦", name: "Blue Square" },
    { emoji: "🟪", name: "Purple Square" },
    { emoji: "🟫", name: "Brown Square" }
];

export default symbolsEmojis;
