/**
 * Emoji RPG Builder - Travel & Places Emoji Data
 * Contains emoji data for the Travel & Places category
 */

const travelEmojis = [
    { emoji: "🚗", name: "automobile" },
    { emoji: "🚕", name: "taxi" },
    { emoji: "🚙", name: "sport utility vehicle" },
    { emoji: "🚌", name: "bus" },
    { emoji: "🚎", name: "trolleybus" },
    { emoji: "🏎️", name: "racing car" },
    { emoji: "🚓", name: "police car" },
    { emoji: "🚑", name: "ambulance" },
    { emoji: "🚒", name: "fire engine" },
    { emoji: "🚐", name: "minibus" },
    { emoji: "🚚", name: "delivery truck" },
    { emoji: "🚛", name: "articulated lorry" },
    { emoji: "🚜", name: "tractor" },
    { emoji: "🛴", name: "kick scooter" },
    { emoji: "🚲", name: "bicycle" },
    { emoji: "🛵", name: "motor scooter" },
    { emoji: "🏍️", name: "motorcycle" },
    { emoji: "🚨", name: "police car light" },
    { emoji: "🚔", name: "oncoming police car" },
    { emoji: "🚍", name: "oncoming bus" },
    { emoji: "🚘", name: "oncoming automobile" },
    { emoji: "🚖", name: "oncoming taxi" },
    { emoji: "🚡", name: "aerial tramway" },
    { emoji: "🚠", name: "mountain cableway" },
    { emoji: "🚟", name: "suspension railway" },
    { emoji: "🚃", name: "railway car" },
    { emoji: "🚋", name: "tram car" },
    { emoji: "🚞", name: "mountain railway" },
    { emoji: "🚝", name: "monorail" },
    { emoji: "🚄", name: "high-speed train" },
    { emoji: "🚅", name: "bullet train" },
    { emoji: "🚈", name: "light rail" },
    { emoji: "🚂", name: "locomotive" },
    { emoji: "🚆", name: "train" },
    { emoji: "🚇", name: "metro" },
    { emoji: "🚊", name: "tram" },
    { emoji: "🚉", name: "station" },
    { emoji: "✈️", name: "airplane" },
    { emoji: "🛫", name: "airplane departure" },
    { emoji: "🛬", name: "airplane arrival" },
    { emoji: "🛩️", name: "small airplane" },
    { emoji: "💺", name: "seat" },
    { emoji: "🛰️", name: "satellite" },
    { emoji: "🚀", name: "rocket" },
    { emoji: "🛸", name: "flying saucer" },
    { emoji: "🚁", name: "helicopter" },
    { emoji: "🛶", name: "canoe" },
    { emoji: "⛵", name: "sailboat" },
    { emoji: "🚤", name: "speedboat" },
    { emoji: "🛥️", name: "motor boat" },
    { emoji: "🛳️", name: "passenger ship" },
    { emoji: "⛴️", name: "ferry" },
    { emoji: "🚢", name: "ship" },
    { emoji: "⚓", name: "anchor" },
    { emoji: "🚧", name: "construction" },
    { emoji: "⛽", name: "fuel pump" },
    { emoji: "🚏", name: "bus stop" },
    { emoji: "🚦", name: "vertical traffic light" },
    { emoji: "🚥", name: "horizontal traffic light" },
    { emoji: "🗿", name: "moai" },
    { emoji: "🗽", name: "Statue of Liberty" },
    { emoji: "🗼", name: "Tokyo tower" },
    { emoji: "🏰", name: "castle" },
    { emoji: "🏯", name: "Japanese castle" },
    { emoji: "🏟️", name: "stadium" },
    { emoji: "🎡", name: "ferris wheel" },
    { emoji: "🎢", name: "roller coaster" },
    { emoji: "🎠", name: "carousel horse" },
    { emoji: "⛱️", name: "umbrella on ground" },
    { emoji: "🏖️", name: "beach with umbrella" },
    { emoji: "🏝️", name: "desert island" },
    { emoji: "⛰️", name: "mountain" },
    { emoji: "🏔️", name: "snow-capped mountain" },
    { emoji: "🗻", name: "mount fuji" },
    { emoji: "🏕️", name: "camping" },
    { emoji: "⛺", name: "tent" },
    { emoji: "🏠", name: "house" },
    { emoji: "🏡", name: "house with garden" },
    { emoji: "🏘️", name: "houses" },
    { emoji: "🏚️", name: "derelict house" },
    { emoji: "🏗️", name: "building construction" },
    { emoji: "🏭", name: "factory" },
    { emoji: "🏢", name: "office building" },
    { emoji: "🏬", name: "department store" },
    { emoji: "🏣", name: "Japanese post office" },
    { emoji: "🏤", name: "post office" },
    { emoji: "🏥", name: "hospital" },
    { emoji: "🏦", name: "bank" },
    { emoji: "🏨", name: "hotel" },
    { emoji: "🏪", name: "convenience store" },
    { emoji: "🏫", name: "school" },
    { emoji: "🏩", name: "love hotel" }
];

export default travelEmojis;
